# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.

# yaml-language-server: $schema=https://raw.githubusercontent.com/espanso/espanso/dev/schemas/match.schema.json

matches:
  # Simple text replacement
  - trigger: ":espanso"
    replace: "Hi there!"

  # NOTE: espanso uses YAML to define matches, so pay attention to the indentation!

  # But matches can also be dynamic:

  # Print the current date
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  # Print the output of a shell command
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo 'Hello from your shell'"

  - trigger: "@@daily-report"
    force_mode: clipboard
    replace: |
      ✅ Yesterday / Last week:

      🎯 Today / In progress:

      🚧 Blockers:

  - trigger: "@@pr-review"
    force_mode: clipboard
    replace: |
      hi @dev__, nhờ mn review review giúp em các PR này nha:
      - ...

  - trigger: "@@pr-release"
    force_mode: clipboard
    replace: |
      dạ em gửi @devops, a @__ PR relase nha:
      - ...

  - trigger: "@@qc-review"
    force_mode: clipboard
    replace: |
      hi @qc__, các card này lên __ ròi ạ, nhờ mn review giúp em nha:
      - ...

  - trigger: "@@title-release-wo"
    force_mode: clipboard
    replace: Release/lumin web optimization x.xx.x

  - trigger: "@@branch-release-wo"
    force_mode: clipboard
    replace: release/lumin-web-optimization-x.xx.

  - trigger: "@@tag-release-wo"
    force_mode: clipboard
    replace: luminoptimization-x.xx.

  - trigger: "@@title-release-pdf"
    force_mode: clipboard
    replace: Release/lumin pdf x.xx.x
  
  - trigger: "@@branch-release-pdf"
    force_mode: clipboard
    replace: release/lumin-pdf-x.xx.x

  - trigger: "@@tag-release-pdf"
    force_mode: clipboard
    replace: luminpdf-x.xx.

  - trigger: "@lfe"
    force_mode: clipboard
    replace: lumin-frontend

  - trigger: "@lbe"
    force_mode: clipboard
    replace: lumin-web-backend

  - trigger: "@lau"
    force_mode: clipboard
    replace: lumin-auth

  - trigger: "@ledfe"
    force_mode: clipboard
    replace: lumin-web-viewer

  - trigger: "@ledbe"
    force_mode: clipboard
    replace: lumin-editor-backend

  # And much more! For more information, visit the docs: https://espanso.org/docs/